/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linyk3.thrift.apply.params;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-4-12")
public class FindEmployInfoParams implements org.apache.thrift.TBase<FindEmployInfoParams, FindEmployInfoParams._Fields>, java.io.Serializable, Cloneable, Comparable<FindEmployInfoParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FindEmployInfoParams");

  private static final org.apache.thrift.protocol.TField EMPLOY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("employId", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FindEmployInfoParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FindEmployInfoParamsTupleSchemeFactory());
  }

  /**
   * 招聘Id 必填
   */
  public String employId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 招聘Id 必填
     */
    EMPLOY_ID((short)1, "employId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EMPLOY_ID
          return EMPLOY_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EMPLOY_ID, new org.apache.thrift.meta_data.FieldMetaData("employId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FindEmployInfoParams.class, metaDataMap);
  }

  public FindEmployInfoParams() {
  }

  public FindEmployInfoParams(
    String employId)
  {
    this();
    this.employId = employId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FindEmployInfoParams(FindEmployInfoParams other) {
    if (other.isSetEmployId()) {
      this.employId = other.employId;
    }
  }

  public FindEmployInfoParams deepCopy() {
    return new FindEmployInfoParams(this);
  }

  @Override
  public void clear() {
    this.employId = null;
  }

  /**
   * 招聘Id 必填
   */
  public String getEmployId() {
    return this.employId;
  }

  /**
   * 招聘Id 必填
   */
  public FindEmployInfoParams setEmployId(String employId) {
    this.employId = employId;
    return this;
  }

  public void unsetEmployId() {
    this.employId = null;
  }

  /** Returns true if field employId is set (has been assigned a value) and false otherwise */
  public boolean isSetEmployId() {
    return this.employId != null;
  }

  public void setEmployIdIsSet(boolean value) {
    if (!value) {
      this.employId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EMPLOY_ID:
      if (value == null) {
        unsetEmployId();
      } else {
        setEmployId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EMPLOY_ID:
      return getEmployId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EMPLOY_ID:
      return isSetEmployId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FindEmployInfoParams)
      return this.equals((FindEmployInfoParams)that);
    return false;
  }

  public boolean equals(FindEmployInfoParams that) {
    if (that == null)
      return false;

    boolean this_present_employId = true && this.isSetEmployId();
    boolean that_present_employId = true && that.isSetEmployId();
    if (this_present_employId || that_present_employId) {
      if (!(this_present_employId && that_present_employId))
        return false;
      if (!this.employId.equals(that.employId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_employId = true && (isSetEmployId());
    list.add(present_employId);
    if (present_employId)
      list.add(employId);

    return list.hashCode();
  }

  @Override
  public int compareTo(FindEmployInfoParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetEmployId()).compareTo(other.isSetEmployId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmployId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.employId, other.employId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FindEmployInfoParams(");
    boolean first = true;

    sb.append("employId:");
    if (this.employId == null) {
      sb.append("null");
    } else {
      sb.append(this.employId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FindEmployInfoParamsStandardSchemeFactory implements SchemeFactory {
    public FindEmployInfoParamsStandardScheme getScheme() {
      return new FindEmployInfoParamsStandardScheme();
    }
  }

  private static class FindEmployInfoParamsStandardScheme extends StandardScheme<FindEmployInfoParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FindEmployInfoParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EMPLOY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.employId = iprot.readString();
              struct.setEmployIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FindEmployInfoParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.employId != null) {
        oprot.writeFieldBegin(EMPLOY_ID_FIELD_DESC);
        oprot.writeString(struct.employId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FindEmployInfoParamsTupleSchemeFactory implements SchemeFactory {
    public FindEmployInfoParamsTupleScheme getScheme() {
      return new FindEmployInfoParamsTupleScheme();
    }
  }

  private static class FindEmployInfoParamsTupleScheme extends TupleScheme<FindEmployInfoParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FindEmployInfoParams struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetEmployId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetEmployId()) {
        oprot.writeString(struct.employId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FindEmployInfoParams struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.employId = iprot.readString();
        struct.setEmployIdIsSet(true);
      }
    }
  }

}

