/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.linyk3.thrift.apply.params;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-4-12")
public class FindExaminationInfoParams implements org.apache.thrift.TBase<FindExaminationInfoParams, FindExaminationInfoParams._Fields>, java.io.Serializable, Cloneable, Comparable<FindExaminationInfoParams> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FindExaminationInfoParams");

  private static final org.apache.thrift.protocol.TField EXAMINATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("examinationId", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FindExaminationInfoParamsStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FindExaminationInfoParamsTupleSchemeFactory());
  }

  /**
   * 笔试Id 必填
   */
  public String examinationId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 笔试Id 必填
     */
    EXAMINATION_ID((short)1, "examinationId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXAMINATION_ID
          return EXAMINATION_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXAMINATION_ID, new org.apache.thrift.meta_data.FieldMetaData("examinationId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FindExaminationInfoParams.class, metaDataMap);
  }

  public FindExaminationInfoParams() {
  }

  public FindExaminationInfoParams(
    String examinationId)
  {
    this();
    this.examinationId = examinationId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FindExaminationInfoParams(FindExaminationInfoParams other) {
    if (other.isSetExaminationId()) {
      this.examinationId = other.examinationId;
    }
  }

  public FindExaminationInfoParams deepCopy() {
    return new FindExaminationInfoParams(this);
  }

  @Override
  public void clear() {
    this.examinationId = null;
  }

  /**
   * 笔试Id 必填
   */
  public String getExaminationId() {
    return this.examinationId;
  }

  /**
   * 笔试Id 必填
   */
  public FindExaminationInfoParams setExaminationId(String examinationId) {
    this.examinationId = examinationId;
    return this;
  }

  public void unsetExaminationId() {
    this.examinationId = null;
  }

  /** Returns true if field examinationId is set (has been assigned a value) and false otherwise */
  public boolean isSetExaminationId() {
    return this.examinationId != null;
  }

  public void setExaminationIdIsSet(boolean value) {
    if (!value) {
      this.examinationId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case EXAMINATION_ID:
      if (value == null) {
        unsetExaminationId();
      } else {
        setExaminationId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case EXAMINATION_ID:
      return getExaminationId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case EXAMINATION_ID:
      return isSetExaminationId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FindExaminationInfoParams)
      return this.equals((FindExaminationInfoParams)that);
    return false;
  }

  public boolean equals(FindExaminationInfoParams that) {
    if (that == null)
      return false;

    boolean this_present_examinationId = true && this.isSetExaminationId();
    boolean that_present_examinationId = true && that.isSetExaminationId();
    if (this_present_examinationId || that_present_examinationId) {
      if (!(this_present_examinationId && that_present_examinationId))
        return false;
      if (!this.examinationId.equals(that.examinationId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_examinationId = true && (isSetExaminationId());
    list.add(present_examinationId);
    if (present_examinationId)
      list.add(examinationId);

    return list.hashCode();
  }

  @Override
  public int compareTo(FindExaminationInfoParams other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetExaminationId()).compareTo(other.isSetExaminationId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExaminationId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.examinationId, other.examinationId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FindExaminationInfoParams(");
    boolean first = true;

    sb.append("examinationId:");
    if (this.examinationId == null) {
      sb.append("null");
    } else {
      sb.append(this.examinationId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FindExaminationInfoParamsStandardSchemeFactory implements SchemeFactory {
    public FindExaminationInfoParamsStandardScheme getScheme() {
      return new FindExaminationInfoParamsStandardScheme();
    }
  }

  private static class FindExaminationInfoParamsStandardScheme extends StandardScheme<FindExaminationInfoParams> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FindExaminationInfoParams struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXAMINATION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.examinationId = iprot.readString();
              struct.setExaminationIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FindExaminationInfoParams struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.examinationId != null) {
        oprot.writeFieldBegin(EXAMINATION_ID_FIELD_DESC);
        oprot.writeString(struct.examinationId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FindExaminationInfoParamsTupleSchemeFactory implements SchemeFactory {
    public FindExaminationInfoParamsTupleScheme getScheme() {
      return new FindExaminationInfoParamsTupleScheme();
    }
  }

  private static class FindExaminationInfoParamsTupleScheme extends TupleScheme<FindExaminationInfoParams> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FindExaminationInfoParams struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetExaminationId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetExaminationId()) {
        oprot.writeString(struct.examinationId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FindExaminationInfoParams struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.examinationId = iprot.readString();
        struct.setExaminationIdIsSet(true);
      }
    }
  }

}

